src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LinkRepository::class)]
class Link
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "URL не может быть пустым")]
    #[Assert\Url(message: "Введён невалидный URL! Проверьте ссылку ещё раз!")]
    private ?string $original_url = null;

    #[ORM\Column(length: 255)]
    private ?string $short_code = null;

    #[ORM\Column]
    private ?\DateTime $creation_date = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $last_click_time_date = null;

    #[ORM\Column(nullable: true)]
    private ?int $click_count = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_one_time = null;

    #[ORM\Column(nullable: true)]
    #[Assert\GreaterThan("+1 minutes", message: "Дата должна быть как минимум на одну минуту больше текущего времени!")]
    private ?\DateTimeImmutable $expiration_date = null;

    public function getIsOneTime(): ?bool
    {
        return $this->is_one_time;
    }

    public function setIsOneTime(?bool $is_one_time): static
    {
        $this->is_one_time = $is_one_time;

        return $this;
    }

    public function getExpirationDate(): ?\DateTimeImmutable
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(?\DateTimeImmutable $expiration_date): static
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOriginalUrl(): ?string
    {
        return $this->original_url;
    }

    public function setOriginalUrl(string $original_url): static
    {
        $this->original_url = $original_url;

        return $this;
    }

    public function getShortCode(): ?string
    {
        return $this->short_code;
    }

    public function setShortCode(string $short_code): static
    {
        $this->short_code = $short_code;

        return $this;
    }

    public function getCreationDate(): ?\DateTime
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTime $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getLastClickTimeDate(): ?\DateTime
    {
        return $this->last_click_time_date;
    }

    public function setLastClickTimeDate(?\DateTime $last_click_time_date): static
    {
        $this->last_click_time_date = $last_click_time_date;

        return $this;
    }

    public function getClickCount(): ?int
    {
        return $this->click_count;
    }

    public function setClickCount(?int $click_count): static
    {
        $this->click_count = $click_count;

        return $this;
    }
}

src/Controller/LinkController.php
<?php

namespace App\Controller;

use App\Entity\Link;
use App\Form\LinkTypeForm;
use App\Repository\LinkRepository;
use Random\RandomException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Класс LinkController для сокращения ссылок
 */
final class LinkController extends AbstractController
{
    /**
     * Главный контроллер, обрабатывающий корневую ссылку '/'
     * @param Request $request принимает http запрос, но данный метод обрабатывает только POST
     * @return Response возвращает сокращенную ссылку и выводит её на страничку
     */
    #[Route('/', name: 'home')]
    public function index(Request $request, LinkRepository $repository): Response
    {
        $shortURL = null;
        $link = new Link();
        $form = $this->createForm(LinkTypeForm::class, $link);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $shortCode = $repository->generateShortCode();

            is_null($link->getExpirationDate()) ?? $link->setExpirationDate(null);
            $link->setClickCount(0);
            $link->setCreationDate(new \DateTime());
            $link->setShortCode($shortCode);

            $repository->persist($link);
            $repository->flush();
            $shortURL = $request->getSchemeAndHttpHost() . '/short/' . $link->getShortCode();
        }

        return $this->render('link/index.html.twig', [
            'form' => $form->createView(),
            'short_url' => $shortURL,
            'error' => NULL,
        ]);

    }

    /**
     * Обработчик для short вида ссылок
     * @param string $code принимает сокращенный код, таким образом метод будет работать не только на localhost
     * @return Response редиректит на оригинальную страничку
     */
    #[Route('/short/{code}', name: 'short')]
    public function shortRedirect(string $code, LinkRepository $repository): Response
    {
        $link = $repository->findByShortCode($code);
        if (!is_null($link)) {
            $originalUrl = $link->getOriginalUrl();
        } else {
            return new Response($this->renderView('link/error.html.twig', ['error' => 'Ошибка! Ссылка никуда не ведёт!']), Response::HTTP_NOT_FOUND );
        }

        if (is_null($originalUrl) || !filter_var($originalUrl, FILTER_VALIDATE_URL)) {
            return $this->render('link/error.html.twig', ['error' => 'Ошибка! Ссылка не найдена!']);
        }

        if ($link->getExpirationDate() < new \DateTimeImmutable() && $link->getExpirationDate() !== null) {
            $repository->remove($link);
            $repository->flush();
            return $this->render('link/error.html.twig', ['error' => 'Ошибка! Срок жизни ссылки истёк!']);
        }

        if ($link->getIsOneTime() === True) {
            $repository->remove($link);
        }
        else {
            $repository->clickUpdate($link);
            $repository->persist($link);
        }
        $repository->flush();

        return new RedirectResponse($originalUrl);
    }

    /**
     * Метод для вывода всех ссылок
     * @param Request $request запрос тут нужен для получения адреса откуда он отправлялся
     * @param LinkRepository $repository репозиторий получается через AutoWiring
     * @return Response
     */
    #[Route('/all', name: 'all')]
    public function all(Request $request, LinkRepository $repository): Response
    {
        $links = $repository->findAll();

        foreach ($links as $link) {
            if ($link->getExpirationDate() < new \DateTimeImmutable() && $link->getExpirationDate() !== null) {
                $repository->remove($link);
                $repository->flush();
            }
        }

        $links = $repository->findAll();

        return $this->render('link/all.html.twig', [
            'links' => $links,
            'short_url_start' => $request->getSchemeAndHttpHost() . '/short/',
        ]);
    }

    /**
     * Обработчик удаления ссылки
     * @param Request $request принимает POST-запрос. Это обработчик на форму.
     * @param LinkRepository $repository репозиторий получается через AutoWiring
     * @return Response перенаправляет на страницу со всеми ссылками
     */
    #[Route('/delete_links', name: 'delete')]
    public function delete(Request $request, LinkRepository $repository): Response
    {
        if ($request->isMethod('POST')) {
            $selected_links = $request->request->all('selected_links') ?? [];
            foreach ($selected_links as $linkId) {
                $repository->remove($repository->find($linkId));
            }
            $repository->flush();
        }

        return $this->redirectToRoute('all');
    }
}

templates/link/all.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Все ссылки!</title>
    {% block stylesheets %}
        <link href="{{ asset('/styles/style.css') }}" type="text/css" rel="stylesheet" />
    {% endblock %}
</head>
<body>
<h1>Все сокращенные ссылки</h1>

{% if links is empty %}
<p>Ссылок ещё не добавлено!</p>
{% else %}
<form action = "delete_links" method="POST">
    <table border="1">
        <thead>
        <tr>
            <th>Выделить</th>
            <th>Оригинальная ссылка</th>
            <th>Короткая ссылка</th>
            <th>Время последнего обращения</th>
            <th>Количество переходов по ссылке</th>
            <th>Тип ссылки</th>
            <th>Дата удаления</th>
        </tr>
        </thead>
        <tbody>
        {% for link in links %}
        <tr>
            <td>
                <input type="checkbox" name="selected_links[]" value="{{ link.id }}" />
            </td>
            <td><a href="{{ link.originalUrl }}">{{ link.originalUrl }}</a></td>
            <td><a href="{{ short_url_start }}{{ link.shortCode }}">{{ short_url_start }}{{ link.shortCode }}</a></td>
            {% if link.lastClickTimeDate%}
                <td>{{ link.lastClickTimeDate |date('H:i:s d.m.Y') }}</td>
            {% else %}
                <td>По ссылке ещё ни разу не переходили!</td>
            {% endif %}
            <td>{{ link.clickCount }}</td>
            {% if link.isOneTime%}
                <td>Одноразовая</td>
            {% else %}
                <td>Многоразовая</td>
            {% endif %}
            {% if link.getExpirationDate()%}
                <td>{{ link.getExpirationDate() |date('H:i:s d.m.Y') }}</td>
            {% else %}
                <td>Бесконечная ссылка!</td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <button type="submit" class="back-button">Удалить выделенные</button>

</form>
{% endif %}
<br>
<a href="{{ path('home') }}" class="back-button">На главную</a>
</body>
</html>

templates/link/error.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Ошибка!</title>
    {% block stylesheets %}
        <link href="{{ asset('/styles/style.css') }}" type="text/css" rel="stylesheet" />
    {% endblock %}
</head>
<body>
<h1> {{ error }} </h1>
<a href="{{ path('all') }}" type="reset" class = "back-button">Все ссылки</a>
<a href="{{ path('home') }}" class="back-button">На главную</a>
</body>
<html>

templates/link/index.html.twig
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сокращение ссылок</title>
    {% block stylesheets %}
        <link href="{{ asset('/styles/style.css') }}" type="text/css" rel="stylesheet" />
    {% endblock %}
</head>
<body>

<h1>Сокращение ссылок</h1>

{{ form_start(form, {'attr': {'class': 'index'}}) }}
    {{ form_row(form.original_url, {'attr': {'class': 'url'}}) }}
    {{ form_row(form.is_one_time, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.expiration_date, {'attr': {'type': 'date'}}) }}
    <button type="submit">Добавить</button>
{{ form_end(form) }}

<a href="{{ path('all') }}" type="reset" class = "back-button">Все ссылки</a>

{% if short_url %}
<p>Короткая ссылка: <a href={{ short_url }}>{{ short_url }}</a></p>
{% endif %}
{% if error %}
<p> Ошибка! {{ error }} </p>
{% endif %}

</body>
</html>